[tessdata]
git-tree-sha1 = "31bf52a4b0217fc12e5d56c780da8e804661a4b7"
lazy = true

    [[tessdata.download]]
    sha256 = "dbc59d8e1de68e90c71cb1f9f0ee05119610df5ad43e6f26f20b907a731774a8"
    url = "https://github.com/ericphanson/SearchablePDFs.jl/releases/download/traineddata/tessdata.tar.gz"

[tessdata_best]
git-tree-sha1 = "752f60d987df86cc91b505936601cdb1988406f8"
lazy = true

    [[tessdata_best.download]]
    sha256 = "3018ba9abbe6ce3f964a32d422e78f66b7395b5e400ea90776b278eee3884fe8"
    url = "https://github.com/ericphanson/SearchablePDFs.jl/releases/download/traineddata/tessdata_best.tar.gz"

[tessdata_fast]
git-tree-sha1 = "8d9094c67ba77459bd6326b07f47c4aba24fa004"
lazy = true

    [[tessdata_fast.download]]
    sha256 = "b97ddd54b0f190bf56d952ac9e3c9cda643537fd98c3122c457097074d9363ee"
    url = "https://github.com/ericphanson/SearchablePDFs.jl/releases/download/traineddata/tessdata_fast.tar.gz"
