name = "SearchablePDFs"
uuid = "78c8a9bf-03de-4425-87c3-987af89136f6"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Poppler_jll = "9c32591e-4766-534b-9725-b71a8799265b"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Tesseract_jll = "efd95c89-babc-5260-8753-618084eaf9d7"
unpaper_jll = "d52248c9-e08a-51c2-9066-05d0bf3e6245"

[compat]
Aqua = "0.5"
CSV = "0.8, 0.9"
Comonicon = "0.11, 0.12"
Poppler_jll = "21.9"
ProgressMeter = "1.5"
Scratch = "1"
Tesseract_jll = "4.1.100"
julia = "1.6"
unpaper_jll = "6.1.100"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
